### ISSUE TITLE
Firebase AppCheckでなんか安全にできそうな話

### ISSUE THREAD

**Issue by naotiki** [Yumemi-Hackathon22-D/DRAW-RUSH#14]
Qiita書いてて気が付きました
[WebアプリでreCAPTCHAv3を使用してアプリチェックを有効にする](https://firebase.google.com/docs/app-check/web/recaptcha-provider?hl=ja&authuser=0)

**Comment by naotiki** [comment]
ローカル環境では動かない
https://firebase.google.com/docs/app-check/web/debug-provider?hl=ja&authuser=0#web-version-9

**Comment by tos-up** [comment]
実装サボったのがバレました
ちゃんと書きます(一応リクエストは認証されて通る)

**Comment by tos-up** [comment]
https://firebase.google.com/docs/app-check/web/debug-provider#localhost
自分でFirebaseに登録してください★

**Comment by naotiki** [comment]
了解です☆

**Comment by tos-up** [comment]
dotenvで安全にしてくれたのでCloseしようカナ？

**Comment by naotiki** [comment]
Closeしまーす！
