### ISSUE TITLE
アクションがあるたびに効果音を流す

### ISSUE THREAD

**Issue by 6mile0** [Yumemi-Hackathon22-D/DRAW-RUSH#15]
Issue失礼します。
こちら実際に体験させて頂いたのですが，相手が描画し終えた際や回答を完了させたことが分かり辛く感じました。
Twitter等徘徊していると気づかないことが多く，円滑なゲーム進行にはもっとアクションごとに通知して(効果音を流すなど)プレイヤーに気づかせる必要があると思います。
よろしくお願いいたします。

**Comment by naotiki** [comment]
🎉
